name = "RelationalAlgebra"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RelationalAlgebra"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib/"
scope = "leanprover"
rev = "v4.24.0"

[[lean_lib]]
name = "RelationalAlgebra"
